### ISSUE TITLE
Changing boot image

### ISSUE THREAD

**Issue by JonasBouchard** [joeferner/voron#1]
Hey! to change the boot image on a btt-pi, your instructions says : "Copy all the files to the Pi", but idk in what directory I should copy all that. Can I get some help please?

**Comment by joeferner** [comment]
Hope these changes help... https://github.com/joeferner/voron/commit/4d6bf31fbd1c20da554a11e713d3fa08bebe249f

Doesn't really matter where you copy them to just needs to be on the Pi, I copied them to a directory in my home directory if I recall.
